### ISSUE TITLE
Improve visibility of auto-completion shortcut

### ISSUE THREAD

**Issue by tferr** [scijava/script-editor-jython#8]
As mentioned in the [forum](https://forum.image.sc/t/jython-auto-completion-of-fiji-methods-in-eclipse-ide/63103/9?u=tferr), it is not obvious that auto-completion requires <kbd>Ctrl</kbd>+<kbd>Space</kbd>. Also, IJM auto-completion does not require it. We should make things more obvious and consistent, by making the shortcut more obvious in the GUI, and by making it optional.

@haesleinhuepf, @ctrueden, @imagejan: Do you know how the IJM auto-completion bypasses <kbd>Ctrl</kbd>+<kbd>Space</kbd>?

**Comment by tferr** [comment]
I did not know that! Neat! To me, <kbd>Ctrl</kbd>+<kbd>Space</kbd> is muscle memory because that's what I'm used to in Eclipse. How do you suggest handling this? Shall we implement the same on the jython side (thus disabling the need for the shortcut combo), or shall it become a formal option somewhere in the GUI? If the latter, I would really need some loose pointers on where to implement that.

pinging @acardona for opinion

**Comment by haesleinhuepf** [comment]
I presume the Eclipse-based developers will have this opinion and IntelliJ-based developers will have that opinion. 

I implemented the auto-completion in a way that it jumps into the face of macro-programmers intentionally. I assume if it wasn't like this, the majority of users would have never discovered that auto-completion exists.

Having an option to switch it to press-CTRL+space-to-auto-complete makes sense though. It could live right next to the checkbox that turns auto-completion completely off:

https://github.com/scijava/script-editor/blob/546062a25625da0cb34dd51af9b98105f7f82ace/src/main/java/org/scijava/ui/swing/script/TextEditor.java#L1463

**Comment by acardona** [comment]
Control+space works, can't add these new features: instead, I spent all my time trying, and failing, to release other features. The mvn build system is broken to the bone is some fundamentally horrible way, and now it stole the time I had to actually add value.

**Comment by imagejan** [comment]
@haesleinhuepf wrote:
> Having an option to switch it to press-CTRL+space-to-auto-complete makes sense though.

Absolutely. I suggested this a while ago here: https://github.com/imagej/imagej-legacy/issues/254

**Comment by tferr** [comment]
Closing this, as it is addressed by PR#56
